### ISSUE TITLE
请问这里的isleap参数的作用是什么？

### ISSUE THREAD

**Issue by roachsinai** [wolfhong/LunarCalendar#7]
https://github.com/wolfhong/LunarCalendar/blob/db3717e06c04a148da87e28be874ff78b9e96e04/lunarcalendar/converter.py#L87

**Comment by dingp** [comment]
flag for 闰月

**Comment by roachsinai** [comment]
> flag for 闰月

lol, I know related to 闰月. But it not work for a test case so I posted this issue.

But now forget the content of that case.

Thanks for reply :)
